name: skydev
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  neon: ^0.1.0
  google_fonts: ^6.1.0
  line_icons: ^2.0.1
  flutter_cube: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/earth/
    - assets/onboarding/